name: Update Action File
description: Simple GitHub action for updating a template file
inputs:
  repository:
    description: |
      The repository to push the changes to.
      Can be obtained from the `github.repository` 
      context.
      Example value is 'alvelive/update-action'
    required: true
  branch:
    description: |
      The branch to push the changes to.
      Can be obtained from the `github.head_ref` context for pull_request or `github.ref_name` for push.
      Example value is 'main', 'user/feture-branch' etc.
    required: true
  sha:
    description: |
      The commit SHA to be used to construct base_url.
      Can be obtained from the `github.sha` context.
    required: true
  template:
    description: The file to read the input from
    required: true
    default: action-template.yml
  output:
    description: The file to write the output to
    required: true
    default: action.yml
  match:
    description: The string to replace
    required: true
    default: '{{base_url}}'
  replace:
    description: The string to replace with
    required: false

runs:
  using: composite
  steps:
    - name: Configure Git
      shell: bash
      run: |
        #!/bin/bash
        set -e

        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Pull latest changes
      shell: bash
      run: |
        #!/bin/bash
        set -e

        git pull --rebase origin "${{ inputs.branch }}"

    - name: Update action file
      shell: bash
      env:
        template: '${{ inputs.template }}'
        output: '${{ inputs.output }}'
        match: '${{ inputs.match }}'
        replace: |
          ${{
            inputs.replace ||
            format(
              'https://raw.githubusercontent.com/{0}/{1}/',
              inputs.repository,
              inputs.sha
            )
          }}
      run: curl -o- https://raw.githubusercontent.com/alvelive/update-script/63e5241bd722cc1504d60477cfdc0c1d2b8a39ec/replace_script.sh | bash

    - name: Commit and push action
      shell: bash
      run: |
        #!/bin/bash
        set -e

        git add '${{ inputs.output }}'
        git commit -m "Update ${{ inputs.output }} to reflect new release"
        git push origin HEAD:${{ github.head_ref }}
